/**
 * CodeAct Types
 * 
 * Types for the CodeAct Agent which generates and executes Playwright code.
 * CodeAct knows Playwright API and translates high-level instructions to code.
 */

/**
 * Execution mode for CodeAct
 */
export type ExecutionMode = 'iterative' | 'script';

/**
 * Code action generated by CodeAct
 */
export interface CodeAction {
  instruction: string;   // High-level instruction from Planner
  thought: string;       // CodeAct's reasoning
  code: string;          // Generated Playwright code
}

/**
 * Result of code execution
 */
export interface CodeResult {
  success: boolean;
  output?: unknown;        // Return value from code
  error?: string;          // Error message if failed
  observation: string;     // Summary of what happened for Planner
  url?: string;            // Current URL after execution
  title?: string;          // Current page title after execution
  
  // Enhanced debugging info for self-repair
  stackTrace?: string;     // Full stack trace when error occurs
  errorType?: string;      // Error type (SyntaxError, TimeoutError, etc.)
  errorLine?: number;      // Line number where error occurred
  logs?: string[];         // Console logs during execution
}

/**
 * CodeAct decision (what LLM returns)
 */
export interface CodeActDecision {
  thought: string;
  code: string;
}

/**
 * Configuration for CodeAct
 */
export interface CodeActConfig {
  mode: ExecutionMode;
  maxCodeLength?: number;
  timeout?: number;
}

/**
 * Default CodeAct configuration
 */
export const DEFAULT_CODEACT_CONFIG: CodeActConfig = {
  mode: 'iterative',
  maxCodeLength: 5000,
  timeout: 30000,
};

